---
apiVersion: v1
kind: Service
metadata:
  name: be-srv
  labels:
    type: be-srv 
spec:
  type: ClusterIP
  ports:
  - name: grpclb
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: be-web
    port: 8081
    protocol: TCP
    targetPort: 8081          
  selector:
    app: be