---
apiVersion: v1
kind: Service
metadata:
  name: be-srv-lb
  labels:
    type: be-srv-lb
spec:
  clusterIP: None
  ports:
  - name: grpclb
    port: 50051
    protocol: TCP
    targetPort: 50051         
  selector:
    app: be