---
apiVersion: v1
kind: Service
metadata:
  name: fe-srv
  labels:
    type: fe-srv
  annotations:
      service.alpha.kubernetes.io/app-protocols: '{"fe":"HTTP2"}'    
spec:
  type: LoadBalancer  
  ports:
  - name: fe
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: fe